{
  "seleniumLog": [],
  "checkPoints": [
    {
      "message": "Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'PC-0023', ip: '192.168.1.4', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_321'\nDriver info: driver.version: AppiumDriver",
      "type": "Fail",
      "screenshot": "",
      "duration": 0,
      "threshold": 0,
      "subCheckPoints": []
    }
  ],
  "errorTrace": "org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.\nBuild info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'\nSystem info: host: 'PC-0023', ip: '192.168.1.4', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_321'\nDriver info: driver.version: AppiumDriver\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:573)\r\n\tat io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)\r\n\tat io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)\r\n\tat io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)\r\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)\r\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:105)\r\n\tat io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:129)\r\n\tat browserStackPages.appSession.openSession(appSession.java:104)\r\n\tat browserStackPages.callCases.setup(callCases.java:25)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)\r\n\tat org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)\r\n\tat org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:623)\r\n\tat org.testng.TestRunner.beforeRun(TestRunner.java:613)\r\n\tat org.testng.TestRunner.run(TestRunner.java:584)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:402)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:304)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1102)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1032)\r\n\tat org.testng.TestNG.run(TestNG.java:1000)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\nCaused by: io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\\Program Files\\nodejs\\node.exe Arguments: [C:\\Users\\NaumanShaikh\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 0.0.0.0] \nProcess output: \u001b[35m[Appium]\u001b[39m Welcome to Appium v2.0.0-rc.4\r\n\u001b[35m[Appium]\u001b[39m Attempting to load driver gecko...\r\n[debug] \u001b[35m[Appium]\u001b[39m Requiring driver at C:\\Users\\NaumanShaikh\\.appium\\node_modules\\appium-geckodriver\r\n\u001b[35m[Appium]\u001b[39m Attempting to load driver uiautomator2...\r\n[debug] \u001b[35m[Appium]\u001b[39m Requiring driver at C:\\Users\\NaumanShaikh\\.appium\\node_modules\\appium-uiautomator2-driver\r\n\u001b[38;5;0m[HTTP]\u001b[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\n\u001b[35m[Appium]\u001b[39m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 0.0.0.0:4723\r\n[debug] \u001b[35m[Appium]\u001b[39m Error: listen EADDRINUSE: address already in use 0.0.0.0:4723\r\n[debug] \u001b[35m[Appium]\u001b[39m     at Server.setupListenHandle [as _listen2] (node:net:1740:16)\r\n[debug] \u001b[35m[Appium]\u001b[39m     at listenInCluster (node:net:1788:12)\r\n[debug] \u001b[35m[Appium]\u001b[39m     at doListen (node:net:1937:7)\r\n[debug] \u001b[35m[Appium]\u001b[39m     at processTicksAndRejections (node:internal/process/task_queues:83:21)\r\n\n\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:161)\r\n\tat io.appium.java_client.remote.AppiumCommandExecutor.lambda$2(AppiumCommandExecutor.java:230)\r\n\tat java.util.Optional.ifPresent(Optional.java:159)\r\n\tat io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:228)\r\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)\r\n\t... 33 more\r\nCaused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://0.0.0.0:4723/wd/hub/status] to be available after 120012 ms\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:125)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:148)\r\n\t... 37 more\r\nCaused by: java.util.concurrent.TimeoutException\r\n\tat java.util.concurrent.FutureTask.get(FutureTask.java:205)\r\n\tat com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:156)\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)\r\n\t... 39 more\r\n"
}